// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yimucgdjwykwefxcfzes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpbXVjZ2Rqd3lrd2VmeGNmemVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjMwMDAsImV4cCI6MjA2MDYzOTAwMH0.2Y1pnXJZmgV8m2dttew4THVo7NeGPsJRfLE1_8b9zcs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);